dist: xenial
language: python
branches:
  only:
    - master
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install

# command to run tests
script: pipenv run python -m pytest
